version: 2.1
parameters:
  workflow_id:
    type: string
    default: '${CIRCLE_WORKFLOW_ID:0:7}'

jobs:
  setup-run-lint:
    docker:
      - image: 'python:3.7.3-stretch'
    working_directory: ~/app
    steps:
      - checkout
      - restore_cache:
          keys:
            - 'v1-dependencies-{{ checksum "requirements.txt" }}'
            - v1-dependencies-
      - run:
          name: install dependencies
          command: |
            python3 -m venv venv
            . venv/bin/activate
            make install
            # Install hadolint
            wget -O /bin/hadolint https://github.com/hadolint/hadolint/releases/download/v1.16.3/hadolint-Linux-x86_64
            chmod +x /bin/hadolint
      - save_cache:
          paths:
            - ./venv
          key: 'v1-dependencies-{{ checksum "requirements.txt" }}'
      - run:
          name: run lint
          command: |
            . venv/bin/activate
            make lint
 
  build-and-push-docker-image:
    docker:
      - image: docker:17.05.0-ce-git
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: Build application Docker image
          command: |
            cd frontend
            docker login -u amalsz -p dytqak-Qusgu8-faqmuh
            docker build -t amalsz/capstone-project .
            docker image ls
            dockerpath="amalsz/capstone-project:v1.0.0"
            docker tag capstone-project ${dockerpath}
            echo "Docker ID and Image: $dockerpath"
            docker push ${dockerpath}

workflows:
  default:
    jobs:
      - setup-run-lint
      - build-and-push-docker-image:
         requires:
            - setup-run-lint
    #  - create-cluster:
    #      cluster-name: capstone-deploy-${CIRCLE_WORKFLOW_ID:0:7}
    #      requires:
    #        - build-docker-images

    #  - test-cluster:
    #      cluster-name: capstone-deploy-${CIRCLE_WORKFLOW_ID:0:7}
    #      requires:
    #        - create-cluster
    
