version: 2

orbs:
  aws-cli: circleci/aws-cli@2.0.3  
  aws-eks: circleci/aws-eks@2.2.0  
  kubernetes: circleci/kubernetes@0.4.0

jobs:
  setup-run-lint:
    docker:
      - image: 'python:3.7.3-stretch'
    working_directory: ~/repo
    steps:
      - checkout
      - restore_cache:
          keys:
            - 'v1-dependencies-{{ checksum "requirements.txt" }}'
            - v1-dependencies-
      - run:
          name: install dependencies
          command: |
            python3 -m venv venv
            . venv/bin/activate
            make install
            # Install hadolint
            wget -O /bin/hadolint https://github.com/hadolint/hadolint/releases/download/v1.16.3/hadolint-Linux-x86_64
            chmod +x /bin/hadolint
      - save_cache:
          paths:
            - ./venv
          key: 'v1-dependencies-{{ checksum "requirements.txt" }}'
      - run:
          name: run lint
          command: |
            . venv/bin/activate
            make lint

workflows:
  default:
    jobs:
      - setup-run-lint
    #  - build-docker-images:
    #     requires:
    #        - setup-run-lint
    #  - create-cluster:
    #      cluster-name: capstone-deploy-${CIRCLE_WORKFLOW_ID:0:7}
    #      requires:
    #        - build-docker-images

    #  - test-cluster:
    #      cluster-name: capstone-deploy-${CIRCLE_WORKFLOW_ID:0:7}
    #      requires:
    #        - create-cluster
    
